### ISSUE TITLE
Error in crossprod(x) :    could not find symbol "..." in environment of the generic function

### ISSUE THREAD

**Issue by habererj** [bwlewis/irlba#11]
I do not understand this error. I have had similar errors like this, which were usually solved by updating R or the package itself. Are there any compatibility issues I am unaware of?

R version 3.1.1 (2014-07-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] irlba_2.0.0  tm_0.6-2     NLP_0.1-8    Matrix_1.2-2

loaded via a namespace (and not attached):
 [1] colorspace_1.2-6 ggplot2_2.1.0    grid_3.1.1       gtable_0.1.2     lattice_0.20-29  munsell_0.4.2    parallel_3.1.1   plyr_1.8.3       Rcpp_0.12.1     
[10] scales_0.3.0     slam_0.1-32      tools_3.1.1

**Comment by bwlewis** [comment]
Hi! Can you provide an example that produces the error? Thanks.

**Comment by habererj** [comment]
Hi, here is some code that produces the error


testtestest<-as.character(c("the drum drumming", "the drum drums","the drum drummer","the drum drummy", "the drum dummy", "the drum drummer"))


testcorp<-VCorpus(VectorSource(testtestest))
inspect(testcorp)
testcorp= tm_map(testcorp,removePunctuation)
testcorp= tm_map(testcorp,tolower)
testcorp= tm_map(testcorp,removeWords, stopwords("english"))

testcorp= tm_map(testcorp, stripWhitespace) 
testcorp= tm_map(testcorp,PlainTextDocument)


dtmtest<-DocumentTermMatrix(testcorp)
findFreqTerms(dtmtest, lowfreq=10)

inspect(testcorp)


sparsedtm<-sparseMatrix(i=dtmtest$i,j=dtmtest$j, x=dtmtest$v)
irlba(sparsedtm,3,maxit = 1000)





> irlba(sparsedtm,3,maxit = 1000)
Error in crossprod(x) : 
  could not find symbol "..." in environment of the generic function

**Comment by bwlewis** [comment]
I'm sorry, but I guess you'll have to provide a bit more context. I am unable to exactly reproduce your code, but this self-contained facsimile works fine, for instance:

```{r}
library(irlba)
sparsedtm < -sparseMatrix(i=sample(100, 100), j=sample(100, 100), x=runif(100))
irlba(sparsedtm, 3, maxit=1000)
```

Can you send the output of `packageDescription("irlba")`?

**Comment by habererj** [comment]
With your sample code, I am getting the same error...

Here is the output of the code you suggested. Thanks!

> packageDescription("irlba")
Package: irlba
Type: Package
Title: Fast Truncated SVD, PCA and Symmetric Eigendecomposition for Large Dense and Sparse Matrices
Version: 2.0.0
Date: 2015-10-09
Author: Jim Baglama and Lothar Reichel
Maintainer: Bryan W. Lewis <blewis@illposed.net>
Description: Fast and memory efficient methods for truncated singular and eigenvalue decompositions and principal component analysis of large sparse or dense
                  matrices.
Depends: Matrix
Imports: stats
License: GPL
BugReports: https://github.com/bwlewis/irlba/issues
NeedsCompilation: no
Packaged: 2015-10-10 16:18:16 UTC; blewis
Repository: CRAN
Date/Publication: 2015-10-11 10:47:33
Built: R 3.1.3; ; 2016-05-03 20:28:55 UTC; windows

-- File: C:/Users/e798335/Documents/rpackages/irlba/Meta/package.rds

**Comment by bwlewis** [comment]
Can you try installing the latest package version?

```{r}
install.packages("irlba")
```

should do it.

**Comment by bwlewis** [comment]
Indeed, CRAN only builds packages for the current R release (at this time 3.4), and the previous *two* versions of R (giving about 1 to 1.5 years of R coverage).  Your version of R is too old for CRAN.

You'll need to install the package from source, which means on Windows you'll need the windows R development tools. The easiest approach to do this is perhaps from the devtools package with:

```{r]
devtools::install_github("bwlewis/irlba")
```

**Comment by habererj** [comment]
I have problems installing things from github, is there somewhere I can download the package and install from the file?

**Comment by bwlewis** [comment]
I build the package for R 3.1x on Windows for you, try this:

```{r}
install.packages("http://illposed.net/irlba_2.1.2.zip", repos=NULL)
```

**Comment by habererj** [comment]
Initial runs are looking good on that build. I greatly appreciate your help
