### ISSUE TITLE
Installation Error on Ubuntu 16.04

### ISSUE THREAD

**Issue by statkclee** [bwlewis/irlba#12]
Hi,

I've got the following error!!! Basically I am trying to install `network3D` package for network analysis.

> install.packages("irlba")
Installing package into ‘/home/rstudio/R/x86_64-pc-linux-gnu-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/irlba_2.1.2.tar.gz'
Content type 'application/x-gzip' length 218471 bytes (213 KB)
==================================================
downloaded 213 KB

* installing *source* package ‘irlba’ ...
** package ‘irlba’ successfully unpacked and MD5 sums checked
** libs
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG   -I"/usr/lib/R/library/Matrix/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c irlb.c -o irlb.o
gcc: error: unrecognized command line option ‘-fstack-protector-strong’
gcc: error: unrecognized command line option ‘-Wdate-time’
/usr/lib/R/etc/Makeconf:132: recipe for target 'irlb.o' failed
make: *** [irlb.o] Error 1
ERROR: compilation failed for package ‘irlba’
* removing ‘/home/rstudio/R/x86_64-pc-linux-gnu-library/3.3/irlba’
Warning in install.packages :
  installation of package ‘irlba’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/Rtmpac9rpA/downloaded_packages’

===================
SessionInfo is as follows;

> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.1 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.3.1

**Comment by bwlewis** [comment]
Yikes. This looks like a problem with your base R installation to me (see, `/usr/lib/R/etc/Makeconf:132`). Or perhaps you have an older compiler installed on your machine?

Are you able to install other source packages that contain compiled code?

I'll try to figure out exactly what's going on and let you know what I find...

**Comment by statkclee** [comment]
@bwlewis 
I installed new R system on AWS ubuntu machine. There was no problem. I guess that what you mentioned was correct. Because I didn't have any issue with your package. Thank you for quick feedback.

**Comment by bwlewis** [comment]
You're welcome.
