### ISSUE TITLE
wrong PC calculated in 2.1.2?

### ISSUE THREAD

**Issue by chenwenan** [bwlewis/irlba#13]
It seems the PCs are not correct. Here is my test:

```
set.seed(1)
x  <- matrix(rnorm(200), nrow=20)
p1 <- prcomp_irlba(x, n=3)
summary(p1)

# Compare with
p2 <- prcomp(x, tol=0.7)
summary(p2)

norm(p1$x - p2$x)
# output [1] 2.566585

norm(scale(x, scale = F) %*% p1$rotation - p2$x)
# output [1] 4.597156e-13
```

**Comment by bwlewis** [comment]
Thanks! Indeed, the returned `x` values are not computed correctly, sorry about this bug. Feel free to submit a PR fixing this; if not I'll work on it this weekend.

Best,

Bryan

**Comment by chenwenan** [comment]
Please go ahead and fix it. Looking forward to the fixed version. Thanks.

**Comment by bwlewis** [comment]
This will appear in version 2.2 on CRAN. You can use the fixed version on github now with `devtools::install_github("bwlewis/irlba")`. Thanks for finding this bug, nice catch!
