### ISSUE TITLE
use NULL/is.null for optional arguments (scale, center, etc.)

### ISSUE THREAD

**Issue by jsams** [bwlewis/irlba#18]
Many of the optional arguments are checked internally using the missing() function. Unfortunately, trying to write a wrapper function where these arguments may or may not be provided is made more difficult with this approach. If you instead set the default values to NULL and checked using is.null() instead, it would be easier to write wrapper functions that optionally use or don't use these arguments. I think this is the standard approach for multi-valued optional arguments like this, insofar as anything in R is standard. Thanks for considering the change!

**Comment by bwlewis** [comment]
OK I will make this change except for the deprecated arguments. I keep some of those around as hidden arguments to maintain backward compatibility as much as possible -- but they should not be used generally.

However FYI  calling wrappers can easily make calls with do.call with or without missing arguments. It's no big deal to me though.
