### ISSUE TITLE
Make the irlba_c routines available for linking

### ISSUE THREAD

**Issue by zdk123** [bwlewis/irlba#37]
I would like to use your wonderful irlba in package I am working on, using constrained svd as a subroutine in some Rcpp / RcppArmadillo code. For large datasets, the overhead of [calling R code from C++ overwhelms](http://gallery.rcpp.org/articles/r-function-from-c++/) computation savings of irlba.

Would you consider making your C code available to be called by other C routines? I am following the advice in [Romain Francois' stackoverflow post](https://stackoverflow.com/questions/29028060/rcpp-call-c-function-from-a-package-within-rcpp), and he links to relevant [R docs](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Linking-to-native-routines-in-other-packages). I am not as clear on how to go about using his hacky solution (capturing the irlba function pointer).

thanks!

**Comment by zdk123** [comment]
As an addendum, I realize that the difficulty here is not necessarily in exposing the C routines but in maintaining integrity of the data/parameter construction if the user is trying to bypass the R interface. If the irlba maintainers predict this would cause too many headaches, feel free to ignore this request, otherwise I may start working on a PR.

**Comment by bwlewis** [comment]
Sorry for the latency, yes I think it's a good idea. Will review and merge later today.

**Comment by bwlewis** [comment]
closing this...a new CRAN release will be out with this very soon.
