### ISSUE TITLE
installation of package ‘irlba’ had non-zero exit status

### ISSUE THREAD

**Issue by sqs1020** [bwlewis/irlba#63]
Hello,

I am trying to install "irlba" on my m1 mac pro and got this error 
Warning message:
In install.packages("irlba") :
  installation of package ‘irlba’ had non-zero exit status

Thanks!

**Comment by bwlewis** [comment]
Can you please supply the output of

sessionInfo()

for your system?

The current CRAN macos-arm64 package checks out OK, see:

https://www.r-project.org/nosvn/R.check/r-release-macos-arm64/irlba-00check.html

**Comment by bwlewis** [comment]
Here is a link to an ARM64 binary for macos of the latest package version 2.3.4 from the r-hub builder (which also checks out OK):

https://artifacts.r-hub.io/irlba_2.3.4.tar.gz-0f6d94ea460b3cfb894ced86cf8583bf/irlba_2.3.4.tgz

you can maybe try downloading and installing that locally.

**Comment by sqs1020** [comment]
Thanks! Problem solved now.

**Comment by senguptanandana** [comment]
Hi, I'm having the same issue but the link for the r-hub builder is no longer available. Can this be reshared?
