### ISSUE TITLE
Python wrapper for IRLBA?

### ISSUE THREAD

**Issue by BrandonKMLee** [bwlewis/irlba#65]
Sorry for asking this, bus it is very tempting to see a new faster implementation of truncated SVD to be made. Could this repo be re-wrapped for python (for testing purposes)?

**Comment by LTLA** [comment]
If you know enough Cython, you could wrap [**CppIrlba**](https://github.com/LTLA/CppIrlba), which ports the C code from the R package into a header-only C++ library. For example, I use this to run IRLBA in web applications, see [here](https://www.npmjs.com/package/scran.js) for an example.

**Comment by BrandonKMLee** [comment]
Thanks for the info, but unfortunately I am not good enough for Cython currently.
